### ISSUE TITLE
(Incorrect test) Doesn't pass 'getting balances'

### ISSUE THREAD

**Issue by RTSTALER** [halva-suite/halva#1]
When starting a test, I get an exception

`(node:16528) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'balances' of undefined`

It is a clean node, launched in dev mode

I do not have a token pallet, this is most likely the case. It’s necessary either to remove the test, or to make a check

**Comment by ByKeks** [comment]
Hi! it could be removed from the base test pipeline. But it should be able to run by request e.g. `npm test -- --example="token"`

**Comment by RTSTALER** [comment]
> Hi! it could be removed from the base test pipeline. But it should be able to run by request e.g. `npm test -- --example="token"`

I agree, cli with selective launch of tests will not be superfluous
